name: CI for Markdown content

on:
  push:
    branches:
      - 'main'
    paths:
      - 'lib/**/*.md'
  pull_request:
    paths:
      - 'lib/**/*.md'
  workflow_dispatch:

jobs:
  lint:
    name: Lint Markdown content

    strategy:
      fail-fast: false

    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 10

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@db43aef879112c3119a410d69f66701e0d530809 # v17.0.0
        with:
          globs: |
            lib/elixir/pages/**/*.md
            README.md
