name: Notify

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-20.04
    name: Notify
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 50
      - uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
        with:
          otp-version: '25.0'
          elixir-version: '1.14.0'
      - name: Run Elixir script
        env:
          ELIXIR_FORUM_TOKEN: ${{ secrets.ELIXIR_FORUM_TOKEN }}
          ELIXIR_LANG_ANN_TOKEN: ${{ secrets.ELIXIR_LANG_ANN_TOKEN }}
        run: |
          elixir .github/workflows/notify.exs ${{ github.ref_name }}
